### ISSUE TITLE
gpt3.5 scroes all input/instruction/response triplets as 4.5

### ISSUE THREAD

**Issue by ghost** [gpt4life/alpagasus#1]
I wonder why all gpt3.5 scores are 4.5. by reading the paper it seems they didn't have that issue for papers study...

**Comment by HuihuiChyan** [comment]
I met the same thing! Any suggestions?

**Comment by Lichang-Chen** [comment]
You need to choose the GPT-3.5-turbo-0301 version as the response quality evaluator.

**Comment by GPT4animal** [comment]
Solved by changing the quality evaluator into "GPT-3.5-turbo-0301"
