### ISSUE TITLE
Fix the GPT-3.5 engine

### ISSUE THREAD

**Issue by Lichang-Chen** [gpt4life/alpagasus#2]
Hi, please use GPT-3.5-turbo-0301 as the response quality evaluator which is the version I used for my paper.

**Comment by mumianyuxin** [comment]
> Hi, please use GPT-3.5-turbo-0301 as the response quality evaluator which is the version I used for my paper.

Hi, Is there any idea of open sourcing your cleaned data? @Lichang-Chen

**Comment by gpt4life** [comment]
Solved! Please refer to the latest version of the code.
