### ISSUE TITLE
Why the triplets of the "claude_52k_scores.json" don't have "### Input" elements?

### ISSUE THREAD

**Issue by qlduNLP** [gpt4life/alpagasus#4]
All the triplets of the "claude_52k_scores.json" don't have "### Input" characters, while the triplets in "alpaca_52k_rating.json" have these elements.

**Comment by GPT4animal** [comment]
Thanks for your question, we've already fixed the problem. Please check the `./data/filtered/claude_t45.json` file, which uses Claude as the filter and filter the data by threshold 4.5
