### ISSUE TITLE
Detail hyperparameters used to reproduce training process

### ISSUE THREAD

**Issue by lirenhao1997** [gpt4life/alpagasus#6]
Really appreciate your effort in this repo!
I'm trying to reproduce the training process and wondering how to set the hyperparameters (like --num_train_epochs or --learning_rate) in your training script for different datasets such as dolly-3k or chatgpt-9k.
I would appreciate it if you would share these details with us. Thanks in advance!

**Comment by GPT4animal** [comment]
Thank you for your interests!
Please refer to the AlpaGasus paper. They describe every hyperparameter very clearly.

**Comment by lirenhao1997** [comment]
> Thank you for your interests! Please refer to the AlpaGasus paper. They describe every hyperparameter very clearly.
Sorry I have ignored that...
Thanks for your reply!
